package planificador.de.procesos;

/**
 *
 * @author Diego Serrano Gómez
 *         Gerardo Ruíz Santana
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    //Declaración e inicialización de ventanas
    VentanaFCFS ventanaFCFS = new VentanaFCFS();
    VentanaRoundRobin ventanaRoundRobin = new VentanaRoundRobin();
    VentanaColasMultiples ventanaColasMultiples = new VentanaColasMultiples();
            
    public MenuPrincipal() {
        initComponents();    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ayuda = new javax.swing.JLabel();
        botonFCFS = new javax.swing.JButton();
        botonRoundRobin = new javax.swing.JButton();
        botonColasMultiples = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planificador de procesos");
        setResizable(false);

        ayuda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ayuda.setText("?");
        ayuda.setToolTipText("Coloca el cursor sobre el botón que tiene el nombre del algoritmo desado para ver una breve descripción del mismo");

        botonFCFS.setText("FCFS");
        botonFCFS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonFCFSMouseClicked(evt);
            }
        });

        botonRoundRobin.setText("RoundRobin");
        botonRoundRobin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRoundRobinMouseClicked(evt);
            }
        });

        botonColasMultiples.setText("Colas multiples");
        botonColasMultiples.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColasMultiplesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ayuda)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonFCFS, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonRoundRobin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonColasMultiples, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ayuda)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonFCFS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRoundRobin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonColasMultiples, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFCFSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFCFSMouseClicked
        //Muestra la ventana ventanaFCFS y oculta la ventana menuPrincipal
        ventanaFCFS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonFCFSMouseClicked

    private void botonRoundRobinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRoundRobinMouseClicked
        //Muestra la ventana ventanaRoundRobin y oculta la ventana menuPrincipal
        ventanaRoundRobin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRoundRobinMouseClicked

    private void botonColasMultiplesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColasMultiplesMouseClicked
        //Muestra la ventana ventanaColasMultiples y oculta la ventana menuPrincipal
        ventanaColasMultiples.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonColasMultiplesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayuda;
    private javax.swing.JButton botonColasMultiples;
    private javax.swing.JButton botonFCFS;
    private javax.swing.JButton botonRoundRobin;
    // End of variables declaration//GEN-END:variables
}
