package planificador.de.procesos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Diego Serrano Gómez
 */
public class VentanaFCFS extends javax.swing.JFrame {

    /**
     * Creates new form FCFS
     */
    //Declaración e inicialización de variables.
    Proceso procesos[] = {new Proceso(), new Proceso(), new Proceso(), new Proceso(), new Proceso()};
    int apuntadorSiguienteProceso = 0;
    Timer intervalo;
    
    //Declaración e inicializador de ejecutadorDeTarea
    ActionListener ejecutadorDeTarea = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        //Cambiar los valores del campo de texto del procesador.
        campoProcesadorNombre.setText(procesos[0].nombre);
        campoProcesadorDuracion.setText(String.valueOf(procesos[0].duracion));
        //Disminuye el valor de la varaible duración hasta -1.
        if(procesos[0].duracion > -1) {
            procesos[0].duracion--;
        }
        //Llamada al método cambio de proceso y al método actualizar si la duración del proceso actual es menor a 0.
        if(procesos[0].duracion == -1) {
            cambioDeProceso();
            actualizar();
        }
        //Detiene la ejecución de la variable de tipo Timer si el valor del campo nombre del proceso es una cadena vacía.
        if("".equals(procesos[0].nombre)){
            campoProcesadorNombre.setText("null");
            campoProcesadorDuracion.setText("null");
            intervalo.stop();
            botonAñadirProceso.setEnabled(true);
        }
      }
    };
    
    
    public VentanaFCFS() {
        initComponents();
        //Inicialización de variable intervalo.
        this.intervalo = new Timer(1000, ejecutadorDeTarea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNombreProceso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoDuracionProceso = new javax.swing.JTextField();
        botonAñadirProceso = new javax.swing.JButton();
        campoNombreProceso1 = new javax.swing.JTextField();
        campoNombreProceso2 = new javax.swing.JTextField();
        campoNombreProceso3 = new javax.swing.JTextField();
        campoNombreProceso4 = new javax.swing.JTextField();
        campoNombreProceso5 = new javax.swing.JTextField();
        campoDuracionProceso1 = new javax.swing.JTextField();
        campoDuracionProceso2 = new javax.swing.JTextField();
        campoDuracionProceso3 = new javax.swing.JTextField();
        campoDuracionProceso4 = new javax.swing.JTextField();
        campoDuracionProceso5 = new javax.swing.JTextField();
        campoProcesadorNombre = new javax.swing.JTextField();
        campoProcesadorDuracion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonEjecutar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerrarVentana(evt);
            }
        });

        jLabel1.setText("Nombre del proceso:");

        jLabel2.setText("Duración del proceso:");

        botonAñadirProceso.setText("Añadir proceso");
        botonAñadirProceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAñadirProcesoMouseClicked(evt);
            }
        });

        campoNombreProceso1.setEditable(false);
        campoNombreProceso1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoNombreProceso2.setEditable(false);
        campoNombreProceso2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoNombreProceso3.setEditable(false);
        campoNombreProceso3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoNombreProceso4.setEditable(false);
        campoNombreProceso4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoNombreProceso5.setEditable(false);
        campoNombreProceso5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoDuracionProceso1.setEditable(false);
        campoDuracionProceso1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoDuracionProceso2.setEditable(false);
        campoDuracionProceso2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoDuracionProceso3.setEditable(false);
        campoDuracionProceso3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoDuracionProceso4.setEditable(false);
        campoDuracionProceso4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoDuracionProceso5.setEditable(false);
        campoDuracionProceso5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoProcesadorNombre.setEditable(false);
        campoProcesadorNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoProcesadorDuracion.setEditable(false);
        campoProcesadorDuracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Procesador");

        botonEjecutar.setText("Ejecutar");
        botonEjecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEjecutarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombreProceso)
                            .addComponent(campoDuracionProceso, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAñadirProceso))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombreProceso1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(campoDuracionProceso1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoDuracionProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDuracionProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(campoNombreProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNombreProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombreProceso4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(campoDuracionProceso4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombreProceso5, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(campoDuracionProceso5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoProcesadorNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoProcesadorDuracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonEjecutar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombreProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoDuracionProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñadirProceso))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombreProceso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreProceso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreProceso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoProcesadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDuracionProceso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDuracionProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDuracionProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDuracionProceso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDuracionProceso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoProcesadorDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEjecutar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAñadirProcesoMouseClicked
        //Adición de procesos al arreglo de procesos.
        procesos[apuntadorSiguienteProceso].nombre = campoNombreProceso.getText();
        procesos[apuntadorSiguienteProceso].duracion = Integer.parseInt(campoDuracionProceso.getText());
        if(apuntadorSiguienteProceso < 4) {
            apuntadorSiguienteProceso++;
        } else {
            botonAñadirProceso.setEnabled(false);
        }
        actualizar();
    }//GEN-LAST:event_botonAñadirProcesoMouseClicked

    private void cerrarVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrarVentana
        //Mostrar ventana menuPrincipal al cerrar esta ventana.
        PlanificadorDeProcesos.menuPrincipal.setVisible(true);
    }//GEN-LAST:event_cerrarVentana

    private void botonEjecutarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEjecutarMouseClicked
        //Ejecución de código en un intervalo de 1 segundo.
        intervalo.start();
    }//GEN-LAST:event_botonEjecutarMouseClicked
    
    //Actualiza el arreglo gráfico de la ventana.
    public void actualizar() {
        campoNombreProceso1.setText(procesos[0].nombre);
        campoDuracionProceso1.setText(String.valueOf(procesos[0].duracion));
        campoNombreProceso2.setText(procesos[1].nombre);
        campoDuracionProceso2.setText(String.valueOf(procesos[1].duracion));
        campoNombreProceso3.setText(procesos[2].nombre);
        campoDuracionProceso3.setText(String.valueOf(procesos[2].duracion));
        campoNombreProceso4.setText(procesos[3].nombre);
        campoDuracionProceso4.setText(String.valueOf(procesos[3].duracion));
        campoNombreProceso5.setText(procesos[4].nombre);
        campoDuracionProceso5.setText(String.valueOf(procesos[4].duracion));
    }
    
    //Ejecuta las acciones necesarias para realizar el proceso de FCFS.
    public void cambioDeProceso() {
        for(int i = 0; i < apuntadorSiguienteProceso; i++) {
            procesos[i].nombre = procesos[i + 1].nombre;
            procesos[i].duracion = procesos[i + 1].duracion;
        }
        procesos[apuntadorSiguienteProceso].nombre = "";
        procesos[apuntadorSiguienteProceso].duracion = 0;
        if(apuntadorSiguienteProceso > 0) {
            apuntadorSiguienteProceso--;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFCFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFCFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFCFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFCFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFCFS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirProceso;
    private javax.swing.JButton botonEjecutar;
    private javax.swing.JTextField campoDuracionProceso;
    private javax.swing.JTextField campoDuracionProceso1;
    private javax.swing.JTextField campoDuracionProceso2;
    private javax.swing.JTextField campoDuracionProceso3;
    private javax.swing.JTextField campoDuracionProceso4;
    private javax.swing.JTextField campoDuracionProceso5;
    private javax.swing.JTextField campoNombreProceso;
    private javax.swing.JTextField campoNombreProceso1;
    private javax.swing.JTextField campoNombreProceso2;
    private javax.swing.JTextField campoNombreProceso3;
    private javax.swing.JTextField campoNombreProceso4;
    private javax.swing.JTextField campoNombreProceso5;
    private javax.swing.JTextField campoProcesadorDuracion;
    private javax.swing.JTextField campoProcesadorNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}