package planificador.de.procesos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Diego Serrano Gómez
 *         Gerardo Ruíz Santana
 */
public class VentanaColasMultiples extends javax.swing.JFrame {

    /**
     * Creates new form VentanaColasMultiples
     */
    
    Proceso procesos[] = {new Proceso(), new Proceso(), new Proceso(), new Proceso(), new Proceso()};
    int apuntadorSiguienteProceso = 0;
    Timer intervalo;
    int contadorDeTurno = 0, apuntadorProcesoEnEjecucion = 0;
    char prioridadActual = 'A';
    
    ActionListener ejecutadorDeTarea = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        campoProcesadorNombre.setText(procesos[apuntadorProcesoEnEjecucion].nombre);
        campoProcesadorDuracion.setText(String.valueOf(procesos[apuntadorProcesoEnEjecucion].duracion));
        cambioDeTurno();
        actualizar();
       
        if("".equals(procesos[0].nombre) && "".equals(procesos[1].nombre) && "".equals(procesos[2].nombre) && "".equals(procesos[3].nombre) && "".equals(procesos[4].nombre)){
            campoProcesadorNombre.setText("null");
            campoProcesadorDuracion.setText("null");
            intervalo.stop();
            apuntadorSiguienteProceso = 0;
            botonAñadirProceso.setEnabled(true);
        }
      }
    };
    
    public VentanaColasMultiples() {
        initComponents();
        this.intervalo = new Timer(1000, ejecutadorDeTarea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoDuracionProceso4 = new javax.swing.JTextField();
        campoDuracionProceso = new javax.swing.JTextField();
        campoDuracionProceso5 = new javax.swing.JTextField();
        botonAñadirProceso = new javax.swing.JButton();
        campoProcesadorNombre = new javax.swing.JTextField();
        campoNombreProceso1 = new javax.swing.JTextField();
        campoProcesadorDuracion = new javax.swing.JTextField();
        campoNombreProceso2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNombreProceso3 = new javax.swing.JTextField();
        botonEjecutar = new javax.swing.JButton();
        campoNombreProceso4 = new javax.swing.JTextField();
        campoNombreProceso5 = new javax.swing.JTextField();
        campoDuracionProceso1 = new javax.swing.JTextField();
        campoNombreProceso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoDuracionProceso2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoDuracionProceso3 = new javax.swing.JTextField();
        etiquetaPrioridadProceso1 = new javax.swing.JLabel();
        etiquetaPrioridadProceso2 = new javax.swing.JLabel();
        etiquetaPrioridadProceso3 = new javax.swing.JLabel();
        etiquetaPrioridadProceso4 = new javax.swing.JLabel();
        etiquetaPrioridadProceso5 = new javax.swing.JLabel();
        campoPrioridadProceso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerrarVentana(evt);
            }
        });

        campoDuracionProceso4.setEditable(false);
        campoDuracionProceso4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoDuracionProceso5.setEditable(false);
        campoDuracionProceso5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botonAñadirProceso.setText("Añadir proceso");
        botonAñadirProceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAñadirProcesoMouseClicked(evt);
            }
        });

        campoProcesadorNombre.setEditable(false);
        campoProcesadorNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoNombreProceso1.setEditable(false);
        campoNombreProceso1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoProcesadorDuracion.setEditable(false);
        campoProcesadorDuracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoNombreProceso2.setEditable(false);
        campoNombreProceso2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Procesador");

        campoNombreProceso3.setEditable(false);
        campoNombreProceso3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botonEjecutar.setText("Ejecutar");
        botonEjecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEjecutarMouseClicked(evt);
            }
        });

        campoNombreProceso4.setEditable(false);
        campoNombreProceso4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoNombreProceso5.setEditable(false);
        campoNombreProceso5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoDuracionProceso1.setEditable(false);
        campoDuracionProceso1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Nombre del proceso:");

        campoDuracionProceso2.setEditable(false);
        campoDuracionProceso2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Duración del proceso:");

        campoDuracionProceso3.setEditable(false);
        campoDuracionProceso3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        etiquetaPrioridadProceso1.setText("A");

        etiquetaPrioridadProceso2.setText("A");

        etiquetaPrioridadProceso3.setText("A");

        etiquetaPrioridadProceso4.setText("A");

        etiquetaPrioridadProceso5.setText("A");

        jLabel9.setText("Prioridad del proceso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombreProceso1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDuracionProceso1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(etiquetaPrioridadProceso1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNombreProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoDuracionProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(etiquetaPrioridadProceso2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNombreProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoDuracionProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(etiquetaPrioridadProceso3)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombreProceso4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDuracionProceso4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(etiquetaPrioridadProceso4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoDuracionProceso5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNombreProceso5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(campoProcesadorDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(campoProcesadorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(etiquetaPrioridadProceso5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonEjecutar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombreProceso, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(campoDuracionProceso)
                            .addComponent(campoPrioridadProceso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAñadirProceso)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombreProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoDuracionProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñadirProceso))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPrioridadProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombreProceso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreProceso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreProceso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoProcesadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDuracionProceso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDuracionProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDuracionProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDuracionProceso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDuracionProceso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoProcesadorDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrioridadProceso1)
                    .addComponent(etiquetaPrioridadProceso2)
                    .addComponent(etiquetaPrioridadProceso3)
                    .addComponent(etiquetaPrioridadProceso4)
                    .addComponent(etiquetaPrioridadProceso5))
                .addGap(10, 10, 10)
                .addComponent(botonEjecutar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAñadirProcesoMouseClicked
        procesos[apuntadorSiguienteProceso].nombre = campoNombreProceso.getText();
        procesos[apuntadorSiguienteProceso].duracion = Integer.parseInt(campoDuracionProceso.getText());
        procesos[apuntadorSiguienteProceso].prioridad = campoPrioridadProceso.getText().toUpperCase().charAt(0);
        if(apuntadorSiguienteProceso < 4) {
            apuntadorSiguienteProceso++;
        } else {
            botonAñadirProceso.setEnabled(false);
        }
        actualizar();
    }//GEN-LAST:event_botonAñadirProcesoMouseClicked

    private void botonEjecutarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEjecutarMouseClicked
        intervalo.start();
    }//GEN-LAST:event_botonEjecutarMouseClicked

    private void cerrarVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrarVentana
        PlanificadorDeProcesos.menuPrincipal.setVisible(true);
    }//GEN-LAST:event_cerrarVentana

    public void actualizar() {
        campoNombreProceso1.setText(procesos[0].nombre);
        campoDuracionProceso1.setText(String.valueOf(procesos[0].duracion));
        etiquetaPrioridadProceso1.setText(String.valueOf(procesos[0].prioridad));
        campoNombreProceso2.setText(procesos[1].nombre);
        campoDuracionProceso2.setText(String.valueOf(procesos[1].duracion));
        etiquetaPrioridadProceso2.setText(String.valueOf(procesos[1].prioridad));
        campoNombreProceso3.setText(procesos[2].nombre);
        campoDuracionProceso3.setText(String.valueOf(procesos[2].duracion));
        etiquetaPrioridadProceso3.setText(String.valueOf(procesos[2].prioridad));
        campoNombreProceso4.setText(procesos[3].nombre);
        campoDuracionProceso4.setText(String.valueOf(procesos[3].duracion));
        etiquetaPrioridadProceso4.setText(String.valueOf(procesos[3].prioridad));
        campoNombreProceso5.setText(procesos[4].nombre);
        campoDuracionProceso5.setText(String.valueOf(procesos[4].duracion));
        etiquetaPrioridadProceso5.setText(String.valueOf(procesos[4].prioridad));
    }
    
    //Ejecuta las acciones necesarias para realizar el proceso de colas múltiples.
    public void cambioDeTurno() {
        for(int i = 0; i < apuntadorSiguienteProceso; i++) {
            if(procesos[i].prioridad == prioridadActual) {
                apuntadorProcesoEnEjecucion = i;
                if(procesos[i].duracion > 0) {
                    procesos[i].duracion--;
                    contadorDeTurno++;
                } else if(procesos[i].duracion == 0) {
                    contadorDeTurno = 0;
                    procesos[i].prioridad = 'F';
                    procesos[i].nombre = "";
                    break;
                }
                if(procesos[i].prioridad != 'E') {
                    if(contadorDeTurno == 2) {
                        procesos[i].prioridad++;
                        contadorDeTurno = 0;
                    }
                }
                break;
            }
            if(i == apuntadorSiguienteProceso - 1 && procesos[apuntadorSiguienteProceso - 1].prioridad != prioridadActual) {
                prioridadActual++;
            }
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaColasMultiples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaColasMultiples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaColasMultiples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaColasMultiples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaColasMultiples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirProceso;
    private javax.swing.JButton botonEjecutar;
    private javax.swing.JTextField campoDuracionProceso;
    private javax.swing.JTextField campoDuracionProceso1;
    private javax.swing.JTextField campoDuracionProceso2;
    private javax.swing.JTextField campoDuracionProceso3;
    private javax.swing.JTextField campoDuracionProceso4;
    private javax.swing.JTextField campoDuracionProceso5;
    private javax.swing.JTextField campoNombreProceso;
    private javax.swing.JTextField campoNombreProceso1;
    private javax.swing.JTextField campoNombreProceso2;
    private javax.swing.JTextField campoNombreProceso3;
    private javax.swing.JTextField campoNombreProceso4;
    private javax.swing.JTextField campoNombreProceso5;
    private javax.swing.JTextField campoPrioridadProceso;
    private javax.swing.JTextField campoProcesadorDuracion;
    private javax.swing.JTextField campoProcesadorNombre;
    private javax.swing.JLabel etiquetaPrioridadProceso1;
    private javax.swing.JLabel etiquetaPrioridadProceso2;
    private javax.swing.JLabel etiquetaPrioridadProceso3;
    private javax.swing.JLabel etiquetaPrioridadProceso4;
    private javax.swing.JLabel etiquetaPrioridadProceso5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
